version: "2"

services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mongo
      - rabbitmq
    command: rabbitmq:5672

  api:
    build: ./Coolector.Api/Coolector.Api
    links:
      - rabbitmq
      - storage-service
    ports:
      - '5000:5000'

  storage-service:
    build: ./Coolector.Services.Storage/Coolector.Services.Storage
    links:
      - mongo
      - rabbitmq
      - users-service
      - remarks-service
      - operations-service
      - statistics-service
    ports:
      - '10000:10000'

  users-service:
    build: ./Coolector.Services.Users/Coolector.Services.Users
    links:
      - mongo
      - rabbitmq
    ports:
      - '10001:10001'

  operations-service:
    build: ./Coolector.Services.Operations/Coolector.Services.Operations
    links:
      - mongo
      - rabbitmq
    ports:
      - '10010:10010'

  mailing-service:
    build: ./Coolector.Services.Mailing/Coolector.Services.Mailing
    links:
      - mongo
      - rabbitmq
    ports:
      - '10005:10005' 

  remarks-service:
    build: ./Coolector.Services.Remarks/Coolector.Services.Remarks
    links:
      - mongo
      - rabbitmq
    ports:
      - '10002:10002'

  signalr-service:
    build: ./Coolector.Services.SignalR/Coolector.Services.SignalR
    links:
      - rabbitmq
    ports:
      - '15000:15000'

  statistics-service:
    build: ./Coolector.Services.Statistics/Coolector.Services.Statistics
    links:
      - mongo
      - rabbitmq
    ports:
      - '10006:10006'  

  supervisor-service:
    build: ./Coolector.Services.Supervisor/Coolector.Services.Supervisor
    links:
      - mongo
      - rabbitmq
      - api
      - mailing-service
      - operations-service
      - remarks-service
      - signalr-service
      - statistics-service
      - storage-service
      - users-service
    ports:
      - '11000:11000'

  mongo:
    image: mongo
    volumes:
      - ./data/mongo:/data/mongo
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - '5672:5672'
      - '15672:15672'
